import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/gameboard.module.css";
import mainStyles from "@/styles/Home.module.css";

import { useState } from "react";
import { useRouter } from 'next/router';

export default function Home() {

  const router = useRouter();

  var amountOfPlayer = [2,3,4];

  var showButton = () =>{
    setShowPlayerButton(prevState => !prevState);
  }

  return (

    
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${mainStyles.main}`}>

        <div className={styles.gameboard}>
        <div>
          <img src="/uno_logo.png" className={styles.unoLogo}/>
        </div>


        ca


        </div>
   
      </main>
    </>
  );
}
